### ISSUE TITLE
Mark dissapear in dropdown at search of multiple words

### ISSUE THREAD

**Issue by Ransche** [wenhoujx/swiper#7]
Hi,

thank you for the fantastic app. It works great. But it seems there is one bug. Why the blue mark in the drop down list disappears if the search contains more than two words? 

![grafik](https://github.com/wenhoujx/swiper/assets/89505604/198325df-46c1-4dc1-97cc-63ac456925bb)

![grafik](https://github.com/wenhoujx/swiper/assets/89505604/a52e5831-5e73-48af-970d-c506dc97b859)

**Comment by wenhoujx** [comment]
hello @Ransche  thanks for using this plugin. 

this "bug" is a limitation of vscode quick-pick only match and highlight exact words. and it's, afaik, impossible to get the highlighting right, due to the lack of vscode API. 

if you search `a b c d`, and a line of `a b c d` matches each single word in exact order, all 4 words are highlighted. 
![image](https://github.com/wenhoujx/swiper/assets/4370201/aad251c1-dedc-4cda-8e4a-b04f7c821a6d)

The quick-pick matching and highlighting is very limited, it doesn't support the rich search syntax of this plugin. 
To force quick-pick dropdown match, the trick i pulled was to do the custom match line by line, then append the user-input search string, e.g. `a b c d`, to the end of the matched line. 

This is why if you have a line `aa bb cc dd` and you search for `a b c d`, this plugin still match, but there is no highlight (it's actually highlighting on the appended user-input search string) 

more info on quick-pick highlighting limitation in this [issue](https://github.com/microsoft/vscode/issues/83424).

**Comment by wenhoujx** [comment]
close b/c impossible with current vscode quickpick api. :(
